In [1]:
import numpy as np

Que 1.  Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.

In [2]:
arr = np.array([0,1,2,3,4,5])
arr

array([0, 1, 2, 3, 4, 5])

In [3]:
print("Data type of arr is :" , arr.dtype)

Data type of arr is : int64


Que 2. Given a NumPy array 'arr', check if its data type is float64.

In [4]:
arr = np.array([1.5, 2.6, 3.7])

if arr.dtype == np.float64:
  print("The data type of arr is float64")
else:
  print("The data type of arr is not float64")

The data type of arr is float64


Que 3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.

In [5]:
arr = np.asarray([12+18j,13+5j,4+9j], dtype=np.complex128)
arr

array([12.+18.j, 13. +5.j,  4. +9.j])

Que 4. Convert an existing NumPy array 'arr' of integers to float32 data type.

In [6]:
arr = np.array([0,1,2,3,4,5])
arr.dtype

dtype('int64')

In [7]:
arr_float32 = arr.astype(np.float32)
arr_float32.dtype

dtype('float32')

Que 5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.

In [8]:
arr = np.array([1.3456342452855,2.96574812036586,3.5485125369584703], dtype=np.float64)
arr

array([1.34563425, 2.96574812, 3.54851254])

In [9]:
arr.dtype

dtype('float64')

In [10]:
arr_float32 = arr.astype(np.float32)
arr_float32.dtype

dtype('float32')

In [11]:
print(arr_float32)

[1.3456342 2.965748  3.5485125]


Que 6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data
type.

In [12]:
def array_attributes(arr):
  print("shape of array is :", arr.shape),
  print("size of array is :", arr.size),
  print("data type of array is :", arr.dtype)

In [13]:
arr

array([1.34563425, 2.96574812, 3.54851254])

In [14]:
array_attributes(arr)

shape of array is : (3,)
size of array is : 3
data type of array is : float64


Que 7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.

In [15]:
def array_dimension(arr):
  return arr.ndim

In [16]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
array_dimension(arr)

2

Que 8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total
size in bytes.

In [18]:
def item_size_info(arr):
  item_size = arr.itemsize
  n_bytes = arr.nbytes
  return 'Item size is', item_size, 'bytes. Total size is', n_bytes, 'bytes.'

In [19]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
item_size_info(arr)

('Item size is', 8, 'bytes. Total size is', 48, 'bytes.')

Que 9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.


In [21]:
def array_strides(arr):
  arr_stride_ = arr.strides
  return arr_stride_

In [22]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [23]:
array_strides(arr)

(24, 8)

Que 10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape
and strides of the array.

In [24]:
def shape_stride_relationship(arr):
  arr_shape = arr.shape
  arr_stride = arr.strides
  return 'Shape of array is', arr_shape, 'Strides of array is', arr_stride

In [25]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
shape_stride_relationship(arr)

('Shape of array is', (3, 3), 'Strides of array is', (24, 8))

Que 11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of
zeros with `n` elements

In [27]:
def create_zeros_array(n):
  return np.zeros(n)

In [28]:
create_zeros_array(7)

array([0., 0., 0., 0., 0., 0., 0.])

Que 12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D
NumPy array filled with ones of size `rows x cols`.

In [29]:
def create_ones_matrix(rows,cols):
  return np.ones((rows,cols))

In [30]:
create_ones_matrix(3,4)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Que 13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and
creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified
`step`

In [31]:
def generate_range_array(start,stop,step):
  return np.arange(start,stop,step)

In [32]:
generate_range_array(1,12,2)

array([ 1,  3,  5,  7,  9, 11])

Que 14. . Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as
arguments and generates a NumPy array with num equally spaced values between `start` and `stop`
(inclusive)

In [33]:
def generate_linear_space(start,stop,num):
  return np.linspace(start,stop,num)

In [34]:
generate_linear_space(1.1,5.5,20)

array([1.1       , 1.33157895, 1.56315789, 1.79473684, 2.02631579,
       2.25789474, 2.48947368, 2.72105263, 2.95263158, 3.18421053,
       3.41578947, 3.64736842, 3.87894737, 4.11052632, 4.34210526,
       4.57368421, 4.80526316, 5.03684211, 5.26842105, 5.5       ])

Que 15.  Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square
identity matrix of size `n x n` using `numpy.eye`

In [35]:
def create_identity_matrix(n):
  return np.eye(n)

In [36]:
create_identity_matrix(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Que 16. Write a function that takes a Python list and converts it into a NumPy array

In [37]:
def convert_to_arr(py_list):
  return np.array(py_list)

In [38]:
convert_to_arr([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Que 17.  Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the
same data.

In [39]:
original_array = np.array([[1,2,3,4],[5,6,7,8]])
original_array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [40]:
view_array = original_array.view()
view_array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [41]:
view_array[0,0] = 101

In [42]:
view_array

array([[101,   2,   3,   4],
       [  5,   6,   7,   8]])

In [43]:
# my original_array also got changed
original_array

array([[101,   2,   3,   4],
       [  5,   6,   7,   8]])

Que 18.  Write a function that takes two NumPy arrays and concatenates them along a specified axis

In [44]:
def concat_array(arr1, arr2, axis=0):
  return np.concatenate((arr1,arr2), axis=axis)

In [45]:
arr_1 = [[1,2],[3,4]]
arr_2 = [[4,3],[2,1]]

In [46]:
concat_array_axis_1 = concat_array(arr_1,arr_2,axis=1)
concat_array_axis_1

array([[1, 2, 4, 3],
       [3, 4, 2, 1]])

In [47]:
concat_array_axis_0 = concat_array(arr_1, arr_2, axis=0)
concat_array_axis_0

array([[1, 2],
       [3, 4],
       [4, 3],
       [2, 1]])

Que 19. Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.concatenate`

In [48]:
arr1 = np.array([[1,2,3],[3,2,1]])
arr2 = np.array([[1,2],[3,4]])

In [49]:
arr1

array([[1, 2, 3],
       [3, 2, 1]])

In [50]:
arr2

array([[1, 2],
       [3, 4]])

In [51]:
np.concatenate((arr1,arr2),axis=1)

array([[1, 2, 3, 1, 2],
       [3, 2, 1, 3, 4]])

Que 20. Write a function that vertically stacks multiple NumPy arrays given as a list

In [52]:
def stack_arrays_vertically(arrays):
  return np.vstack(arrays)

In [53]:
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
array3 = np.array([[9, 10], [11, 12]])

stacked_array = stack_arrays_vertically([array1, array2, array3])
stacked_array

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

Que 21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive)
with a given step size.

In [54]:
def create_int_array(start,stop,step):
  return np.arange(start,stop+1,step)

In [55]:
create_int_array(1,28,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27])

Que 22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1
(inclusive)

In [56]:
def equally_spaced_values():
  return np.linspace(0,1,10)

In [57]:
equally_spaced_values()

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

Que. 23.  Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and
1000 (inclusive)

In [58]:
def log_spaced_values():
  return np.logspace(0, 3, num=5, endpoint=True)

In [59]:
log_spaced_values()

array([   1.        ,    5.62341325,   31.6227766 ,  177.827941  ,
       1000.        ])

Que 24.  Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values
are random integers between 1 and 100.

In [60]:
import pandas as pd
import numpy as np

In [61]:
arr = np.random.randint(1,100,(5,3))
arr

array([[72, 74, 33],
       [ 3,  7, 38],
       [15, 89, 40],
       [72, 35, 81],
       [72, 37, 56]])

In [62]:
df = pd.DataFrame(arr)
df

0   1   2
0  72  74  33
1   3   7  38
2  15  89  40
3  72  35  81
4  72  37  56

Que 25.  Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column
with zeros. Use NumPy operations within the Pandas DataFrame

In [63]:
def replace_negatives_with_zeros(df, column_name):
  df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])
  return df

In [64]:
df =  pd.DataFrame({
    "col1" : [1,2,3],
    "col2" : [4,5,6],
    "col3" : [-1,-4,8]
})
df

col1  col2  col3
0     1     4    -1
1     2     5    -4
2     3     6     8

In [65]:
replace_negatives_with_zeros(df, "col3")

col1  col2  col3
0     1     4     0
1     2     5     0
2     3     6     8

Que 26. Access the 3rd element from the given NumPy array.

In [66]:
arr = np.array([10, 20, 30, 40, 50])

In [67]:
arr

array([10, 20, 30, 40, 50])

In [68]:
arr[2]

30

Que 27. Retrieve the element at index (1, 2) from the 2D NumPy array

In [69]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [70]:
# Here index (1,2) means row at index 1 and column at index 2.
arr_2d[1,2]

6

Que 28.  Using boolean indexing, extract elements greater than 5 from the given NumPy array.

In [71]:
arr = np.array([3, 8, 2, 10, 5, 7])

In [72]:
arr

array([ 3,  8,  2, 10,  5,  7])

In [73]:
arr[arr > 5]

array([ 8, 10,  7])

Que 29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.

In [74]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
arr[2:6]

array([3, 4, 5, 6])

Que 30.  Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.

In [76]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [77]:
sub_arr = arr_2d[0:2,1:]
sub_arr

array([[2, 3],
       [5, 6]])

Que 31. Write a NumPy function to extract elements in specific order from a given 2D array based on indices
provided in another array.

In [78]:
def extract_element_by_indices(array_2d, indices):
  flatten_array = array_2d.flatten()
  extracted_array = flatten_array[indices]
  return extracted_array

In [79]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [80]:
indices = np.array([1,2])

In [81]:
extract_element_by_indices(arr_2d, indices)

array([2, 3])

Que 32.  Create a NumPy function that filters elements greater than a threshold from a given 1D array using
boolean indexing.

In [82]:
def filter_elements_by_boolean(arr,boolean_):
  return arr[arr > boolean_]

In [83]:
arr = np.array([1,2,3,4,5,6,7,8,9])
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
# Here, I want values greater than 4
filter_elements_by_boolean(arr,4)

array([5, 6, 7, 8, 9])

Que 33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three
separate arrays for each dimension.

In [85]:
def extract_elements_3d_array(array_3d, indices_dim1, indices_dim2, indices_dim3):
   extracted_elements = array_3d[indices_dim1, indices_dim2, indices_dim3]
   return extracted_elements

In [86]:
# Example usage:
array_3d = np.array([[[1, 2, 3],
                      [4, 5, 6]],
                     [[7, 8, 9],
                      [10, 11, 12]]])

indices_dim1 = np.array([0, 1])
indices_dim2 = np.array([0, 1])
indices_dim3 = np.array([1, 2])


In [87]:
extracted_elements = extract_elements_3d_array(array_3d, indices_dim1, indices_dim2, indices_dim3)

In [88]:
extracted_elements

array([ 2, 12])

Que 34. Write a NumPy function that returns elements from an array where both two conditions are satisfied
using boolean indexing.

In [89]:
def return_element_two_boolean(arr,bool1,bool2):
  combined_condition = bool1 & bool2
  return arr[combined_condition]

In [90]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:


return_element_two_boolean(arr,arr<8,arr%2==0)

array([2, 4, 6])

Que 35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided
in separate arrays.

In [92]:
def extract_row_col_index(arr_2d,row_index,col_index):
  return arr_2d[[row_index],[col_index]]

In [93]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [94]:
row_index = np.array([1,2])
col_index = np.array([0,1])


In [95]:
extract_row_col_index(arr_2d,row_index,col_index)

array([[4, 8]])

Que 36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

In [96]:
arr = np.arange(1,10).reshape(3,3)

In [97]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [98]:
arr + 5

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

Que 37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the
corresponding element in arr1 using NumPy broadcasting.

In [99]:
arr1 = np.array([[2, 3, 4]])
arr2 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])


In [100]:
# Here we need to transpose arr1 so that the multiplication will be possible


arr1.T * arr2

array([[ 2,  4,  6,  8],
       [15, 18, 21, 24],
       [36, 40, 44, 48]])

Que 38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using
NumPy broadcasting.

In [101]:
arr1 = np.array([[2, 3, 4, 5]])
arr2 = np.array([[1, 2, 3],
                 [5, 6, 7],
                 [9, 10, 11],
                 [12,13, 14]])


In [102]:
# Here also we have to transpose the arr1.
arr1.T + arr2


array([[ 3,  4,  5],
       [ 8,  9, 10],
       [13, 14, 15],
       [17, 18, 19]])

Que 39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy
broadcasting.

In [103]:
arr1 = np.array([[1],[2],[3]])
arr2 = np.array([[1,2,3]])

In [104]:
arr1.T + arr2

array([[2, 4, 6]])

Que 40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy
broadcasting. Handle the shape incompatibility.

In [105]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[1,2],[1,2]])

In [106]:
# Reshape arr1 to (2, 3, 1) to align its shape properly for broadcasting
arr1_reshaped = arr1[:, :, np.newaxis]  # Shape: (2, 3, 1)

In [107]:
arr1_reshaped

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [108]:
# Reshape arr2 to (2, 1, 2) to align its shape properly for broadcasting
arr2_reshaped = arr2[:, np.newaxis, :]  # Shape: (2, 1, 2)

In [109]:
arr2_reshaped

array([[[1, 2]],

       [[1, 2]]])

In [110]:
arr1_reshaped * arr2_reshaped

array([[[ 1,  2],
        [ 2,  4],
        [ 3,  6]],

       [[ 4,  8],
        [ 5, 10],
        [ 6, 12]]])

Que 41.  Calculate column wise mean for the given array:

In [111]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [112]:
np.mean(arr, axis=0)

array([2.5, 3.5, 4.5])

Que 42. Find maximum value in each row of the given array:

In [113]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [114]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [115]:
np.max(arr, axis=1)

array([3, 6])

Que 43.  For the given array, find indices of maximum value in each column.

In [116]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [117]:
np.argmax(arr, axis = 0)

array([1, 1, 1])

Que 44. For the given array, apply custom function to calculate moving sum along rows.

In [118]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [119]:
def moving_sum(arr):
    return np.cumsum(arr)

In [120]:
moving_sum(arr)

array([ 1,  3,  6, 10, 15, 21])

Que 45. In the given array, check if all elements in each column are even

In [121]:
arr = np.array([[2, 4, 6], [3, 5, 7]])
arr

array([[2, 4, 6],
       [3, 5, 7]])

In [122]:
all_even = np.all(arr % 2 == 0, axis=0)

In [123]:
all_even

array([False, False, False])

Que 46.  Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the
reshaped matrix.

In [124]:
original_array = np.array([1, 2, 3, 4, 5, 6])
original_array

array([1, 2, 3, 4, 5, 6])

In [125]:
np.mat(original_array.reshape(3,2))

matrix([[1, 2],
        [3, 4],
        [5, 6]])

Que 47.  Create a function that takes a matrix as input and returns the flattened array.

In [126]:
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
input_matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [127]:
def return_flattened_arr(mat):
  return np.array(mat).flatten()

In [128]:
return_flattened_arr(input_matrix)

array([1, 2, 3, 4, 5, 6])

Que 48. Write a function that concatenates two given arrays along a specified axis.

In [129]:
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])


In [130]:
array1

array([[1, 2],
       [3, 4]])

In [131]:
array2

array([[5, 6],
       [7, 8]])

In [132]:
def concatenate_arr(arr1, arr2, axis):
  return concat_array(arr1, arr2, axis=axis)


In [133]:
concatenate_arr(array1, array2, 1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [134]:
concatenate_arr(array1, array2, 0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

Que 49.  Create a function that splits an array into multiple sub-arrays along a specified axis.

In [135]:
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
original_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [136]:
def split_array(original_array, axis, num_splits):
    # Split the array along the specified axis
    sub_arrays = np.split(original_array, num_splits, axis=axis)
    return sub_arrays

In [137]:
split_array(original_array, 1, 3)

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

Que 50.  Write a function that inserts and then deletes elements from a given array at specified indices.

In [138]:
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]


In [139]:
def insert_and_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete):
    # Insert elements at specified indices
    for index, value in zip(indices_to_insert, values_to_insert):
        original_array = np.insert(original_array, index, value)

    # Delete elements at specified indices
    original_array = np.delete(original_array, indices_to_delete)

    return original_array


In [140]:
modified_array = insert_and_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete)
modified_array

array([ 1, 10, 11,  4,  5])

Que 51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10.
Perform element-wise addition between `arr1` and `arr2`

In [141]:
arr1 = np.random.randint(1, 10, (3,3))
arr2 = np.random.randint(1, 10, (3,3))

In [142]:
arr1, arr2

(array([[5, 2, 9],
        [6, 1, 6],
        [8, 7, 8]]),
 array([[7, 6, 7],
        [9, 5, 6],
        [6, 8, 7]]))

In [143]:
arr1 + arr2

array([[12,  8, 16],
       [15,  6, 12],
       [14, 15, 15]])

Que 52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers
from 1 to 10. Subtract `arr2` from `arr1` element-wise

In [144]:
arr1 = np.arange(10,0,-1)
arr2 = np.arange(1,11)

In [145]:
arr1 - arr2

array([ 9,  7,  5,  3,  1, -1, -3, -5, -7, -9])

Que 53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5.
Perform element-wise multiplication between `arr1` and `arr2`.

In [146]:
arr1 = np.random.randint(1, 5, (3,3))
arr2 = np.random.randint(1, 5, (3,3))

In [147]:
arr1, arr2

(array([[1, 3, 3],
        [1, 3, 1],
        [3, 2, 4]]),
 array([[4, 4, 1],
        [2, 4, 1],
        [4, 1, 4]]))

In [148]:
arr1 * arr2

array([[ 4, 12,  3],
       [ 2, 12,  1],
       [12,  2, 16]])

Que 54.  Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1
to 5. Perform element-wise division of `arr1` by `arr2`.

In [149]:
arr1 = np.arange(2,12,step=2)
arr2 = np.arange(1,6)

In [150]:
arr1,  arr2

(array([ 2,  4,  6,  8, 10]), array([1, 2, 3, 4, 5]))

In [151]:
arr1 / arr2

array([2., 2., 2., 2., 2.])

Que 55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers
reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.

In [152]:
arr1 = np.arange(1,6)
arr2 = np.arange(5,0,-1)

In [153]:
arr1,  arr2

(array([1, 2, 3, 4, 5]), array([5, 4, 3, 2, 1]))

In [154]:
arr1 ** arr2

array([ 1, 16, 27, 16,  5])

Que 56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.

In [155]:
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
arr

array(['hello', 'world', 'hello', 'numpy', 'hello'], dtype='<U5')

In [156]:
def count_substring_occurrences(arr, substring):
    count = 0
    for string in arr:
        count += string.count(substring)
    return count


In [157]:
count_substring_occurrences(arr, 'hello')

3

Que 57.  Write a function that extracts uppercase characters from a NumPy array of strings.

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

In [158]:
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

In [159]:
arr

array(['Hello', 'World', 'OpenAI', 'GPT'], dtype='<U6')

In [160]:
def extract_uppercase_chars(arr):
    uppercase_chars = ''
    for string in arr:
        uppercase_chars += ''.join([char for char in string if char.isupper()])
    return uppercase_chars

In [161]:
extract_uppercase_chars(arr)

'HWOAIGPT'

Que 58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.

In [162]:
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [163]:
def replace_substring(arr, old_substring, new_substring):
    # Create an empty list to store modified strings
    modified_strings = []

    # Loop through each string in the array
    for string in arr:
        # Replace occurrences of old_substring with new_substring in the current string
        modified_string = string.replace(old_substring, new_substring)
        # Append the modified string to the list
        modified_strings.append(modified_string)

    # Convert the list of modified strings into a NumPy array
    return np.array(modified_strings)

In [164]:
replace_substring(arr, 'apple', 'Apple' )

array(['Apple', 'banana', 'grape', 'pineApple'], dtype='<U9')

Que 59. Write a function that concatenates strings in a NumPy array element-wise.

In [165]:
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

In [166]:
def concatenate_element_wise(arr1, arr2):
  return np.char.add(arr1,arr2)

In [167]:
concatenate_element_wise(arr1, arr2)

array(['HelloOpen', 'WorldAI'], dtype='<U9')

Que 60. Write a function that finds the length of the longest string in a NumPy array.

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [168]:
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
arr

array(['apple', 'banana', 'grape', 'pineapple'], dtype='<U9')

In [169]:
def longest_string_length(arr):
    # Convert the NumPy array to a list of strings
    string_list = arr.tolist()
    # Find the length of the longest string
    longest_length = max(len(string) for string in string_list)
    return longest_length

In [170]:
longest_string_length(arr)

9

Que 61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and
standard deviation of the dataset using NumPy's functions

In [171]:
arr1 = np.random.randint(1, 1000, 100)

In [172]:
arr1

array([806, 415, 340, 425, 230, 369, 386, 619, 278, 887, 341, 206, 889,
       534, 557, 648, 514, 412, 216, 377, 302, 699, 820, 323, 750, 151,
       434, 322, 466, 380, 239, 429,  41, 919, 928, 555, 928, 232, 381,
       221,  99, 192, 674, 122, 401, 126, 963, 692, 538, 842, 808, 324,
       380, 718, 914, 565, 405, 255, 543,   9, 584, 287,  41, 211, 831,
       992, 878, 668, 891, 461, 447,  86, 351, 682, 399, 384, 309, 577,
       688, 572, 687, 327, 704, 230, 531, 710,  35, 137, 537, 118, 711,
        67, 767, 583, 230,  28, 404, 972, 579, 735])

In [173]:
np.mean(arr1)

479.7

In [174]:
np.median(arr1)

431.5

In [175]:
np.var(arr1)

68437.69

In [176]:
np.std(arr1)

261.6059823474991

Que 62.  Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the
dataset.

In [177]:
arr1 = np.random.randint(1, 100, 50)
arr1

array([94, 79, 64, 92,  4, 64, 83, 84, 97,  7, 50, 64, 18, 39, 45, 85, 50,
       10, 96, 49, 58, 86, 35, 21, 28, 59, 85, 80, 62, 27, 80, 30, 97,  6,
       66, 16,  5, 46, 34, 96, 25, 35, 10, 67, 78, 10, 73, 96,  9, 89])

In [178]:
np.percentile(arr1, q = 25)

27.25

In [179]:
np.percentile(arr1, q = 75)

82.25

Que 63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these
arrays using NumPy's `corrcoef` function.

In [180]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([5, 4, 3, 2, 1])

In [181]:
# Compute the correlation coefficient between the two arrays
correlation_coefficient = np.corrcoef(array1, array2)[0, 1]

In [182]:
correlation_coefficient

-0.9999999999999999

Que 64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.

In [183]:
mat1 = np.matrix([[1,2],[3,4]])
mat2 = np.matrix([[5,6],[7,8]])

In [184]:
mat1.dot(mat2)

matrix([[19, 22],
        [43, 50]])

Que 65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th
percentiles along with the first and third quartiles.

In [185]:
arr1 = np.random.randint(10, 1000, 50)
arr1

array([713, 315, 209, 497, 822, 383, 665, 396, 989, 855, 141, 761, 639,
       902, 449, 190,  70, 519, 655, 153, 863, 357,  24, 455, 637, 811,
       747, 928, 793, 240, 210,  38, 621, 359, 322, 482,  81, 556,  49,
       530, 586, 427, 798, 593, 244, 969, 429, 175, 677, 262])

In [186]:
np.percentile(arr1,10)

135.00000000000003

In [187]:
np.percentile(arr1,50)

489.5

In [188]:
np.percentile(arr1,90)

855.8

In [189]:
np.percentile(arr1,25)

248.5

In [190]:
np.percentile(arr1,75)

704.0

Que 66.  Create a NumPy array of integers and find the index of a specific element.

In [191]:
arr = np.array([1,2,3,4])

In [192]:
arr

array([1, 2, 3, 4])

In [193]:
np.where(arr == 2)[0]

array([1])

Que. 67 Generate a random NumPy array and sort it in ascending order

In [194]:
arr = np.random.rand(10)
arr

array([0.61772228, 0.83682029, 0.04298696, 0.47460162, 0.37579167,
       0.79930746, 0.83296186, 0.35793463, 0.65102252, 0.47023287])

In [195]:
np.sort(arr)

array([0.04298696, 0.35793463, 0.37579167, 0.47023287, 0.47460162,
       0.61772228, 0.65102252, 0.79930746, 0.83296186, 0.83682029])

Que 68. Filter elements >20  in the given NumPy array.

In [196]:
arr = np.array([12, 25, 6, 42, 8, 30])
arr

array([12, 25,  6, 42,  8, 30])

In [197]:
arr[arr > 20]

array([25, 42, 30])

Que 69. Filter elements which are divisible by 3 from a given NumPy array.

In [198]:
arr = np.array([1, 5, 8, 12, 15])
arr

array([ 1,  5,  8, 12, 15])

In [199]:
arr[arr % 3 == 0]

array([12, 15])

Que 70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array

In [200]:
arr = np.array([10, 20, 30, 40, 50])
arr

array([10, 20, 30, 40, 50])

In [201]:
arr[(arr >= 20) & (arr <= 40)]

array([20, 30, 40])

Que 71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder.

In [202]:
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [203]:
arr.dtype.byteorder

'='

Que 72.  For the given NumPy array, perform byte swapping in place using `byteswap()`.

In [204]:
arr = np.array([1, 2, 3], dtype=np.int32)
arr

array([1, 2, 3], dtype=int32)

In [205]:
arr.byteswap(True)

array([16777216, 33554432, 50331648], dtype=int32)

Que 73.  For the given NumPy array, swap its byte order without modifying the original array using
`newbyteorder()`.

In [206]:
arr = np.array([1, 2, 3], dtype=np.int32)
arr

array([1, 2, 3], dtype=int32)

In [207]:
new_arr = arr.newbyteorder()

In [208]:
new_arr

array([16777216, 33554432, 50331648], dtype='>i4')

In [209]:
arr

array([1, 2, 3], dtype=int32)

Que 74. For the given NumPy array and swap its byte order conditionally based on system endianness using
`newbyteorder()`.

In [210]:
import numpy as np
import sys

In [211]:
arr = np.array([1, 2, 3], dtype=np.int32)
arr

array([1, 2, 3], dtype=int32)

In [212]:
new_arr = arr.newbyteorder() if sys.byteorder == 'little' else arr

In [213]:
new_arr

array([16777216, 33554432, 50331648], dtype='>i4')

Que 75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype`
attribute `byteorder`.

In [214]:
arr = np.array([1, 2, 3], dtype=np.int32)
arr

array([1, 2, 3], dtype=int32)

In [215]:
# Check if byte swapping is necessary
byte_swap_needed = arr.dtype.byteorder != '='

if byte_swap_needed:
    print("Byte swapping is necessary for the current system.")
else:
    print("Byte swapping is not necessary for the current system.")

Byte swapping is not necessary for the current system.


Que 76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify
an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.

In [216]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

There are two ways of creating copy of an array first is shallow copy and second is deep copy.

In [217]:
# shallow copy
copy_arr = arr
copy_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [218]:
copy_arr[1] = 101

In [219]:
copy_arr

array([  1, 101,   3,   4,   5,   6,   7,   8,   9,  10])

In [220]:
arr   # here arr also got changed because copy_arr and arr points out to the same memory space.

array([  1, 101,   3,   4,   5,   6,   7,   8,   9,  10])

In [221]:
# deep copy
copy_arr = arr.copy()
copy_arr

array([  1, 101,   3,   4,   5,   6,   7,   8,   9,  10])

In [222]:
copy_arr[5] = 105
copy_arr

array([  1, 101,   3,   4,   5, 105,   7,   8,   9,  10])

In [223]:
arr     # now arr didn't changed because we used deep copy concept.

array([  1, 101,   3,   4,   5,   6,   7,   8,   9,  10])

Que 77.  Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from
the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.

In [224]:
mat = np.matrix(np.random.randint(1,10,(3,3)))
mat

matrix([[8, 3, 8],
        [8, 2, 1],
        [1, 7, 4]])

In [225]:
view_slice = mat[:2, :2]
view_slice

matrix([[8, 3],
        [8, 2]])

In [226]:
view_slice[0,0]=1812
view_slice

matrix([[1812,    3],
        [   8,    2]])

In [227]:
mat   # here the original matrix got changed because the slice view is a view of the original data, and modifying it modifies the original data as well

matrix([[1812,    3,    8],
        [   8,    2,    1],
        [   1,    7,    4]])

Que 78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice
`view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.

In [228]:
array_a = np.arange(1,13).reshape(4,3)
array_a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [229]:
view_b = array_a[:3, :2]
view_b

array([[1, 2],
       [4, 5],
       [7, 8]])

In [230]:
view_b + 5

array([[ 6,  7],
       [ 9, 10],
       [12, 13]])

In [231]:
array_a     # array_a didn't change because broadcasting operations on a slice view, sometimes NumPy may create a copy
            # instead of modifying the original array in place, especially if the broadcasting changes the shape of the slice view

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

Que 79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view
`reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it
reflects changes in the original `orig_array`.

In [232]:
orig_array = np.arange(1,9).reshape(2,4)
orig_array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [233]:
reshaped_view = orig_array[:2, :2]
reshaped_view

array([[1, 2],
       [5, 6]])

In [234]:
reshaped_view[0,0] = 100
reshaped_view

array([[100,   2],
       [  5,   6]])

In [235]:
orig_array    # clearly, we can see the orig_array got changed because reshaped_view was just a view of orig_view

array([[100,   2,   3,   4],
       [  5,   6,   7,   8]])

Que 80.  Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of
elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.

In [236]:
data = np.array(np.random.randint(1,20,(3,4)))
data

array([[13, 12, 10, 14],
       [14,  8,  7, 19],
       [ 8, 11,  9,  5]])

In [237]:
data_copy = data[data > 5]
data_copy

array([13, 12, 10, 14, 14,  8,  7, 19,  8, 11,  9])

In [238]:
data_copy[1] = 101
data_copy

array([ 13, 101,  10,  14,  14,   8,   7,  19,   8,  11,   9])

In [239]:
data    # it does not affect the data, this happens because data_copy is a separate copy of the data, not a view of the original data.

array([[13, 12, 10, 14],
       [14,  8,  7, 19],
       [ 8, 11,  9,  5]])

Que 81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction
operations between them.

In [240]:
matrix_A = np.matrix(np.random.randint(1,10,(3,3)))
matrix_B = np.matrix(np.random.randint(1,10,(3,3)))

In [241]:
matrix_A,     matrix_B

(matrix([[9, 6, 5],
         [2, 4, 5],
         [1, 4, 4]]),
 matrix([[7, 9, 1],
         [1, 6, 6],
         [9, 4, 9]]))

In [242]:
matrix_A + matrix_B

matrix([[16, 15,  6],
        [ 3, 10, 11],
        [10,  8, 13]])

In [243]:
matrix_A - matrix_B

matrix([[ 2, -3,  4],
        [ 1, -2, -1],
        [-8,  0, -5]])

Que 82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.

In [244]:
C = np.matrix(np.random.randint(1,10,(3,2)))
D = np.matrix(np.random.randint(1,10,(2,4)))

In [245]:
C,   D

(matrix([[7, 6],
         [5, 5],
         [5, 7]]),
 matrix([[1, 8, 3, 8],
         [3, 9, 5, 5]]))

In [246]:
C @ D

matrix([[ 25, 110,  51,  86],
        [ 20,  85,  40,  65],
        [ 26, 103,  50,  75]])

Que 83. Create a matrix `E` and find its transpose.

In [247]:
E = np.matrix([1,2,3,4,5])
E

matrix([[1, 2, 3, 4, 5]])

In [248]:
E.T

matrix([[1],
        [2],
        [3],
        [4],
        [5]])

Que 84.  Generate a square matrix `F` and compute its determinant.

In [249]:
F = np.matrix(np.random.randint(1,11,(3,3)))
F

matrix([[10,  3,  2],
        [ 7,  5,  2],
        [ 8,  1,  8]])

In [250]:
np.linalg.det(F)

194.00000000000003

Que 85.  Create a square matrix `G` and find its inverse.

In [251]:
G = np.matrix(np.random.randint(1,10,(2,2)))
G

matrix([[4, 1],
        [9, 9]])

In [252]:
np.linalg.inv(G)

matrix([[ 0.33333333, -0.03703704],
        [-0.33333333,  0.14814815]])